// Code generated by MockGen. DO NOT EDIT.
// Source: creator.go
//
// Generated by this command:
//
//	mockgen -source=creator.go -destination=../mock/creator.mock.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mongo "go.mongodb.org/mongo-driver/mongo"
	options "go.mongodb.org/mongo-driver/mongo/options"
	gomock "go.uber.org/mock/gomock"
)

// MockiCreator is a mock of iCreator interface.
type MockiCreator[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockiCreatorMockRecorder[T]
}

// MockiCreatorMockRecorder is the mock recorder for MockiCreator.
type MockiCreatorMockRecorder[T any] struct {
	mock *MockiCreator[T]
}

// NewMockiCreator creates a new mock instance.
func NewMockiCreator[T any](ctrl *gomock.Controller) *MockiCreator[T] {
	mock := &MockiCreator[T]{ctrl: ctrl}
	mock.recorder = &MockiCreatorMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiCreator[T]) EXPECT() *MockiCreatorMockRecorder[T] {
	return m.recorder
}

// Many mocks base method.
func (m *MockiCreator[T]) InsertMany(ctx context.Context, docs []T) (*mongo.InsertManyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMany", ctx, docs)
	ret0, _ := ret[0].(*mongo.InsertManyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Many indicates an expected call of Many.
func (mr *MockiCreatorMockRecorder[T]) Many(ctx, docs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMany", reflect.TypeOf((*MockiCreator[T])(nil).InsertMany), ctx, docs)
}

// ManyWithOptions mocks base method.
func (m *MockiCreator[T]) InsertManyWithOptions(ctx context.Context, docs []T, opts ...*options.InsertManyOptions) (*mongo.InsertManyResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, docs}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertManyWithOptions", varargs...)
	ret0, _ := ret[0].(*mongo.InsertManyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ManyWithOptions indicates an expected call of ManyWithOptions.
func (mr *MockiCreatorMockRecorder[T]) ManyWithOptions(ctx, docs any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, docs}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertManyWithOptions", reflect.TypeOf((*MockiCreator[T])(nil).InsertManyWithOptions), varargs...)
}

// One mocks base method.
func (m *MockiCreator[T]) InsertOne(ctx context.Context, docs T) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOne", ctx, docs)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// One indicates an expected call of One.
func (mr *MockiCreatorMockRecorder[T]) One(ctx, docs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockiCreator[T])(nil).InsertOne), ctx, docs)
}

// OneWithOptions mocks base method.
func (m *MockiCreator[T]) InsertOneWithOptions(ctx context.Context, doc T, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, doc}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOneWithOptions", varargs...)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OneWithOptions indicates an expected call of OneWithOptions.
func (mr *MockiCreatorMockRecorder[T]) OneWithOptions(ctx, doc any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, doc}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOneWithOptions", reflect.TypeOf((*MockiCreator[T])(nil).InsertOneWithOptions), varargs...)
}
