// Generated by optioner -type BeforeOpContext; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/chenmingyong0423/go-optioner

package creator

import (
	"go.mongodb.org/mongo-driver/mongo"
)

type BeforeOpContextOption[T any] func(*BeforeOpContext[T])

func NewBeforeOpContext[T any](col *mongo.Collection, opts ...BeforeOpContextOption[T]) *BeforeOpContext[T] {
	beforeOpContext := &BeforeOpContext[T]{
		Col: col,
	}

	for _, opt := range opts {
		opt(beforeOpContext)
	}

	return beforeOpContext
}

func WithDoc[T any](doc *T) BeforeOpContextOption[T] {
	return func(beforeOpContext *BeforeOpContext[T]) {
		beforeOpContext.Doc = doc
	}
}

func WithDocs[T any](docs []*T) BeforeOpContextOption[T] {
	return func(beforeOpContext *BeforeOpContext[T]) {
		beforeOpContext.Docs = docs
	}
}
