// Generated by optioner -type OpContext; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/chenmingyong0423/go-optioner

package operation

import (
	"go.mongodb.org/mongo-driver/mongo"
)

type OpContextOption func(*OpContext)

func NewOpContext(col *mongo.Collection, opts ...OpContextOption) *OpContext {
	opContext := &OpContext{
		Col: col,
	}

	for _, opt := range opts {
		opt(opContext)
	}

	return opContext
}

func WithDoc(doc any) OpContextOption {
	return func(opContext *OpContext) {
		opContext.Doc = doc
	}
}

func WithFilter(filter any) OpContextOption {
	return func(opContext *OpContext) {
		opContext.Filter = filter
	}
}

func WithReplacement(replacement any) OpContextOption {
	return func(opContext *OpContext) {
		opContext.Replacement = replacement
	}
}

func WithUpdate(update any) OpContextOption {
	return func(opContext *OpContext) {
		opContext.Updates = update
	}
}
