// Generated by optioner -type BeforeOpContext; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/chenmingyong0423/go-optioner

package deleter

import (
	"go.mongodb.org/mongo-driver/mongo"
)

type BeforeOpContextOption func(*BeforeOpContext)

func NewBeforeOpContext(col *mongo.Collection, filter any, opts ...BeforeOpContextOption) *BeforeOpContext {
	beforeOpContext := &BeforeOpContext{
		Col:    col,
		Filter: filter,
	}

	for _, opt := range opts {
		opt(beforeOpContext)
	}

	return beforeOpContext
}
