// Generated by optioner -type AfterOpContext; DO NOT EDIT
// If you have any questions, please create issues and submit contributions at:
// https://github.com/chenmingyong0423/go-optioner

package deleter

import (
	"go.mongodb.org/mongo-driver/mongo"
)

type AfterOpContextOption func(*AfterOpContext)

func NewAfterOpContext(col *mongo.Collection, filter any, opts ...AfterOpContextOption) *AfterOpContext {
	afterOpContext := &AfterOpContext{
		Col:    col,
		Filter: filter,
	}

	for _, opt := range opts {
		opt(afterOpContext)
	}

	return afterOpContext
}
